CREATE TABLE ES_LOTE(
	ID_LOTE INT IDENTITY PRIMARY KEY,
	NM_LOTE VARCHAR(100) NOT NULL,
	DH_REGISTRO DATETIME NOT NULL,
)
GO
CREATE TABLE  ES_METODOLOGIA_AVALIACAO(
        ID_METODO_AVALIACAO INT IDENTITY PRIMARY KEY,
		DS_METODO_AVALIACAO NVARCHAR(100) NOT NULL,
        DH_REGISTRO DATETIME NOT NULL,
		QT_MINIMA INT NOT NULL,
        AGRUPAMENTO NVARCHAR(50) NOT NULL,
        QT_CALCULO INT NOT NULL,
		TP_CALCULO NVARCHAR(50) NOT NULL,
        ID_LOTE INT NOT NULL,
		FOREIGN KEY (ID_LOTE) REFERENCES ES_LOTE(ID_LOTE)
)
GO
CREATE TABLE ES_TIPO_PARAMETRO(
	ID_TIPO_PARAMETRO INT IDENTITY PRIMARY KEY,
	DS_TIPO_PARAMETRO VARCHAR(50) NOT NULL
)
GO
CREATE TABLE ES_PARAMETRO(
	 ID_PARAMETRO INT IDENTITY PRIMARY KEY
     ,DS_PARAMETRO VARCHAR(100) NOT NULL
     ,VALOR_NOMINAL FLOAT
     ,LIMITE_INFERIOR FLOAT
     ,LIMITE_SUPERIOR FLOAT
	 ,ID_LOTE INT NOT NULL
     ,ID_TIPO_PARAMETRO INT
	 ,FOREIGN KEY (ID_TIPO_PARAMETRO) REFERENCES ES_TIPO_PARAMETRO(ID_TIPO_PARAMETRO)
)
GO
CREATE TABLE ES_ENSAIO_QUALIDADE(
 ID_ENSAIO_QUALIDADE  INT IDENTITY PRIMARY KEY,
 ID_LOTE INT NOT NULL,
 ID_PARAMETRO INT NOT NULL,
 DH_REGISTRO DATETIME NOT NULL,
 NR_ORDEM INT NOT NULL,
 VL_QUANTITATIVO DECIMAL,
 VL_QUALITATIVO DECIMAL,
)
GO

